name: MetaCubeXD
version: "1.241.3-4"
slug: metacubexd
description: MetaCubeXD UI for Mihomo
url: https://github.com/Tabstone/ha_addons/tree/main/metacubexd
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:view-dashboard
panel_title: MetaCubeXD
map:
  - all_addon_configs:rw
ports:
  9395/tcp: 80
ports_description:
  9395/tcp: MetaCubeXD web UI
