name: MetaCubeXD
version: "1.243.2-1"
slug: metacubexd
description: MetaCubeXD UI for Mihomo
url: https://github.com/Tabstone/ha_addons/tree/main/metacubexd
arch:
  - amd64
  - aarch64
init: false
map:
  - all_addon_configs:rw
ports:
  80/tcp: 9395
ports_description:
  80/tcp: MetaCubeXD web UI
webui: http://[HOST]:[PORT:80]/
