name: MetaCubeXD
version: "1.241.3-1"
slug: metacubexd
description: MetaCubeXD UI for Mihomo
url: https://github.com/Tabstone/ha_addons/tree/main/metacubexd
arch:
  - amd64
  - aarch64
init: false
map:
  - all_addon_configs:rw
ports:
  9097/tcp: 80
ports_description:
  9097/tcp: MetaCubeXD web UI
